softhub/urls.py
from django.conf.urls import url, include
from rest_framework.routers import DefaultRouter
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from .rest_api.view_set import *
from .views.SofthubIndex import SofthubIndex
from .views.ApplicationDetail import ApplicationDetail
from .views.ApplicationUpload import ApplicationUpload
from .views.ApplicationUpdate import ApplicationUpdate
from .views.VersionUpdate import VersionUpdate
from .views.VersionUpload import VersionUpload
from .views.ExecutableUpload import ExecutableUpload
from .views.ExecutableUpdate import ExecutableUpdate
from .views.UserCreation import UserCreation
from .views.AboutTemplateView import AboutTemplateView
from .views.SearchView import SearchView
from .views.UserProfile import UserProfile
from .views.UserUpdate import UserUpdate


app_name = 'softhub'

urlpatterns = [
    ##################
    # Template Views #
    ##################
    url(
        r'^$',
        SofthubIndex.as_view(),
        name='index'),

    url(
        r'^about$',
        AboutTemplateView.as_view(),
        name='about'),

    url(
        r'^search/$',
        SearchView.as_view(),
        name='search'),

    url(
        r'^user/$',
        login_required(UserProfile.as_view()),
        name='user_profile'
    ),

    ##################
    # Detail Views   #
    ##################
    url(r'^app/(?P<pk>[0-9]+)/$',
        ApplicationDetail.as_view(),
        name='app_detail'),

    ##################
    # Create Views   #
    ##################
    url(r'^upload/app/$',
        # Note: login is required, the check is done inside the
        # ApplicationUpload class with a decorator.
        ApplicationUpload.as_view(),
        name='app_upload'),

    url(r'^upload/app_version/(?P<pk>[0-9]+)$',
        login_required(VersionUpload.as_view()),
        name='app_version_upload'),

    url(r'^upload/app_executable/(?P<pk>[0-9]+)$',
        login_required(ExecutableUpload.as_view()),
        name='app_executable_upload'),

    ##################
    # Update Views   #
    ##################
    url(r'^app/update/(?P<pk>[0-9]+)/$',
        login_required(ApplicationUpdate.as_view()),
        name='app_update'),

    url(r'^app/update/version/(?P<pk>[0-9]+)$',
        login_required(VersionUpdate.as_view()),
        name='version_update'),

    url(r'^app/update/executable/(?P<pk>[0-9]+)$',
        login_required(ExecutableUpdate.as_view()),
        name='executable_update'),

    url(r'^user/update/(?P<pk>[0-9]+)/$',
        login_required(UserUpdate.as_view()),
        name='user_update'),
]


# Authentication URLS
# https://docs.djangoproject.com/en/1.10/topics/auth/default/#module-django.contrib.auth.views
urlpatterns += [
    url(r'^', include('django.contrib.auth.urls')),

    url(r'^register/',
        UserCreation.as_view(),
        name='create_user'),
]


# REST router
router = DefaultRouter()
router.register(r'os', OperatingSystemViewSet)
router.register(r'app', ApplicationViewSet)
router.register(r'version', VersionViewSet)
router.register(r'executable', ExecutableViewSet)
router.register(r'developer', DeveloperViewSet)

# DISABLED REST API for the moment
# urlpatterns += [
#     url(r'^api/',
#         include(router.urls)),
# ]

softhub_site/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from softhub_site.views.LandingPage import LandingPage


urlpatterns = [
    url(r'^$', LandingPage.as_view(), name='landing-page'),
    url(r'^softhub/', include('softhub.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

softhub/views/AboutTemplateView.py
from django.views.generic import TemplateView


class AboutTemplateView(TemplateView):
    template_name = 'softhub/about/about.html'

softhub/views/ApplicationDetail.py
from django.views.generic import DetailView
# from django import forms
from django.core.exceptions import PermissionDenied
from django.views.generic import FormView, CreateView
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse

from softhub.models.Application import Application
from softhub.models.Executable import Executable
from softhub.models.Version import Version
from softhub.models.Review import Review
from softhub.views.ReviewForm import ReviewForm
from softhub.views.ReviewUpload import ReviewUpload


class ApplicationDetail(DetailView):
    model = Application
    context_object_name = 'app'
    template_name = 'softhub/application_detail/application_detail.html'

    def post(self, request, *args, **kwargs):
        view = ReviewUpload.as_view()
        return view(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ApplicationDetail, self).get_context_data(**kwargs)
        app = self.get_object()

        # an alternate method is to get the URL parameter, as explained here:
        # https://stackoverflow.com/questions/15754122/url-parameters-and-logic-in-django-class-based-views-templateview#15754497
        # app_id = self.kwargs['pk']

        exes = app.get_latest_executables()
        os_exe_dict = {}
        for e in exes:
            if e.release_platform.family == 'linux':
                context['linux'] = e
            elif e.release_platform.family == 'osx':
                context['osx'] = e
            elif e.release_platform.family == 'windows':
                context['windows'] = e

        context['versions'] = Version.objects.filter(application_id=app.id)
        context['executables'] = Executable.objects.filter(
            version__application_id=app.id)

        context['form'] = ReviewForm()
        context['reviews'] = \
            Review.objects.filter(
                application=self.get_object()).order_by('-date')
        if self.request.user.is_authenticated():
            context['user_reviewed_app'] = \
                Review.userReviewedApplication(self.request.user, app)

        context['apps'] = Application.getRecommendedApps(self.object)

        return context

softhub/views/ApplicationForm.py
from django.forms import ModelForm

from softhub.models.Application import Application
from softhub.models.Developer import Developer


class ApplicationForm(ModelForm):
    def __init__(self, user_id=None, *args, **kwargs):
        self.user_id = user_id
        super(ModelForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Application
        exclude = ['developer']

    def save(self, commit=True):
        # TODO review this method: do I need to add some error management?
        app = super(ApplicationForm, self).save(commit=False)
        dev = Developer.objects.get(user__id=self.user_id)
        app.developer = dev
        app.save()

        return app

softhub/views/ApplicationUpdate.py
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied

from softhub.models.Application import Application
from softhub.views.ApplicationForm import ApplicationForm
from softhub.models.Developer import Developer


class ApplicationUpdate(UpdateView):
    model = Application
    form_class = ApplicationForm
    template_name = 'softhub/application_form/application_update_form.html'
    context_object_name = 'app'
    # template_name_suffix = '_update_form'
    # success_url = reverse_lazy('softhub:index')

    def dispatch(self, request, *args, **kwargs):
        appId = kwargs.get('pk')
        app = Application.objects.get(id=appId)
        dev = Developer.objects.get(user_id=request.user)

        # if somebody try to access this URL/view but is not the owner of the
        # app
        if not app.ownedByDev(dev):
            raise PermissionDenied()
        else:
            return super(
                ApplicationUpdate,
                self).dispatch(request, *args, **kwargs)

    def get_form(self):
        """ Override method to pass user_id parameter to the form
        """
        from softhub.views.ApplicationUpload import get_form_with_user_id_kwarg
        return get_form_with_user_id_kwarg(self)

softhub/views/ApplicationUpload.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.core.exceptions import PermissionDenied

from softhub.models.Application import Application
from softhub.views.ApplicationForm import ApplicationForm


class ApplicationUpload(CreateView):
    model = Application
    form_class = ApplicationForm
    success_url = reverse_lazy('softhub:index')
    template_name = 'softhub/application_form/application_form.html'

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        # if somebody try to access this URL/view but is not a developer
        if not self.request.user.isDeveloper():
            raise PermissionDenied()
        else:
            return super(CreateView, self).dispatch(request, *args, **kwargs)

    def get_form(self):
        """ Override method to pass user_id parameter to the form
        """
        return get_form_with_user_id_kwarg(self)


def get_form_with_user_id_kwarg(obj):
    """ Get the form object and adds a user_id keyword argument; returns the
    form.

    This method is shared by ApplicationUpdate and ApplicationUpload classes.

    Parameters
    ----------
    obj : ApplicationUpload object
    """
    form_class = obj.get_form_class()
    kwargs = obj.get_form_kwargs()
    kwargs['user_id'] = obj.request.user.id
    form = form_class(**kwargs)

    return form

softhub/views/ExecutableForm.py
from django.forms import ModelForm, ValidationError

from softhub.models.Executable import Executable
from softhub.models.OperatingSystem import OperatingSystem


class ExecutableForm(ModelForm):
    class Meta:
        model = Executable
        exclude = []

    def clean(self):
        """ Method ovverride to prevent the upload of more than one executable
        for a given operating system.
        Shows an error in the form if the executable for the given
        version-application already exists.
        """
        # TODO this could be handled via AJAX on client side.

        cleaned_data = super().clean()

        release_platform = cleaned_data.get('release_platform')
        version = cleaned_data.get('version')

        executables = Executable.objects.filter(version_id=version.id)

        operating_systems_with_an_executable = list()
        for exe in executables:
            operating_systems_with_an_executable.append(exe.release_platform)

        if release_platform in operating_systems_with_an_executable:
            msg = ('An executable for version=['
                   + str(version) + '] on '
                   + release_platform.__str__()
                   + ' is already stored on the DB')
            self.add_error('release_platform', msg)

softhub/views/ExecutableUpdate.py
from django.views.generic import UpdateView
from django.core.exceptions import PermissionDenied
from django.urls import reverse

from softhub.models.Executable import Executable
from softhub.models.Developer import Developer
from softhub.models.Version import Version


class ExecutableUpdate(UpdateView):
    model = Executable
    fields = ['version', 'release_platform', 'info', 'executable_file']
    template_name = 'softhub/executable_form/executable_update.html'
    context_object_name = 'executable'

    def dispatch(self, request, *args, **kwargs):
        executableId = kwargs.get('pk')
        executable = Executable.objects.get(id=executableId)
        app = executable.version.application

        dev = Developer.objects.get(user_id=request.user)

        # if somebody try to access this URL/view but is not the owner of the
        # version
        if not app.ownedByDev(dev):
            raise PermissionDenied()
        else:
            return super(
                ExecutableUpdate,
                self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        exe = self.get_object()
        return reverse('softhub:app_detail',
                       kwargs={'pk': exe.version.application.id})

    def get_form(self):
        """ Shows only the current application's versions.
        Override to filter the default queryset
        https://docs.djangoproject.com/en/1.10/ref/class-based-views/mixins-editing/#formmixin
        """

        form_class = self.get_form_class()
        form = form_class(**self.get_form_kwargs())

        if self.request.method == 'GET':
            app = self.get_object()

            # Filter the Version items inserted in the HTML select tag input,
            # modifying the default queryset that include all the Version
            # objects.
            # Select only the versions of the application id passed via a GET
            # parameter.
            form.fields['version'].queryset = (  # TODO change in 'versions'
                Version.objects.filter(application_id=app.id))

        return form

softhub/views/ExecutableUpload.py
from django.urls import reverse
from django.utils import timezone
from django.views.generic import CreateView

from softhub.models.Executable import Executable
from softhub.views.ExecutableForm import ExecutableForm
from softhub.models.Application import Application
from softhub.models.Version import Version


class ExecutableUpload(CreateView):
    model = Executable
    form_class = ExecutableForm
    template_name = 'softhub/executable_form/executable_form.html'

    def get_context_data(self, **kwargs):
        """ Add 'app' to the context template's variables """

        context = super(ExecutableUpload, self).get_context_data(**kwargs)
        context['app'] = self.get_object()

        return context

    def get_form(self):
        """ Override to filter the default queryset

        https://docs.djangoproject.com/en/1.10/ref/class-based-views/mixins-editing/#formmixin
        """

        form_class = self.get_form_class()
        form = form_class(**self.get_form_kwargs())

        # TODO check if there is a better way of doing this
        # maybe with another method in ExecutableForm ?
        # https://docs.djangoproject.com/en/1.10/topics/class-based-views/intro/#using-class-based-views
        # def get(self, request):
        #    <view logic>
        #    return HttpResponse('result')
        if self.request.method == 'GET':
            app = self.get_object()

            # Filter the Version items inserted in the HTML select tag input,
            # modifying the default queryset that include all the Version
            # objects.
            # Select only the versions of the application id passed via a GET
            # parameter.
            form.fields['version'].queryset = (  # TODO change in 'versions'
                Version.objects.filter(application_id=app.id))

        return form

    def get_initial(self):
        initial = {}
        v = self.get_object().get_latest_version()
        if v is not None:
            initial['version'] = v.id
        return initial

    def get_object(self):
        """
        By default get_object() would return an Executable with id equals to
        the <pk> parameter passed from the URL; overriding this method should
        change the object returned.

        Note that the <pk> argument passed from the HTML is equal to app.id.
        """

        app_id = self.kwargs.get('pk')
        return Application.objects.get(id=app_id)

    def get_success_url(self):
        app = self.get_object()
        return reverse('softhub:app_detail', kwargs={'pk': app.id})

softhub/views/ReviewForm.py
from django import forms

from softhub.models.Review import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        exclude = ['application', 'user']

softhub/views/ReviewUpload.py
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.urls import reverse

from softhub.models.Application import Application
from softhub.models.Review import Review
from softhub.views.ReviewForm import ReviewForm


class ReviewUpload(CreateView):
    model = Review
    form_class = ReviewForm
    template_name = 'softhub/application_detail/application_detail.html'

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print(self.get_form())
        return super(ReviewUpload, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        """ Adds missing attributes to Review object and raise an exception if
        the user already reviewed the application.
        """
        if Review.userReviewedApplication(
            self.request.user,
            self.get_object()
        ):
            raise Exception(
                'User '
                + str(self.request.user)
                + ' already uploaded a review for '
                + str(self.get_object())
            )

        # self.object is a Review object
        self.object = form.save(commit=False)
        self.object.application = self.get_object()
        self.object.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            'softhub:app_detail', kwargs={'pk': self.get_object().pk})

    def get_object(self):
        return Application.objects.get(id=self.kwargs.get('pk'))

softhub/templates/softhub/application_detail/components/app_details_panels.html
<div class="col-md-6">

  <ul class="list-group">
    <li class="list-group-item">
      Latest Version
      <span class="pull-right"> {{ app.get_latest_version }}</span>
    </li>

    <li class="list-group-item">
      Updated
      <span class="pull-right"> {{ app.get_latest_version.release_date|default:"Never" }} </span>
    </li>

    <li class="list-group-item">
      Category <span class="pull-right">{{ app.category }}</span>
    </li>

    <li class="list-group-item">
      Website
      <span class="pull-right"> <a href="{{ app.website }}">{{ app.website }}</a></span>
    </li>

    <li class="list-group-item">
      License
      <span class="pull-right"> {{ app.get_latest_version.license|default:"No license" }}</span>
    </li>
  </ul>

</div>

softhub/templates/softhub/application_detail/components/app_developer_actions.html
<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title">Developer Actions</h3>
  </div>

  <div class="panel-body">
    <div class="col-md-12">
      <p>
        <a href="{% url 'softhub:app_version_upload' app.id %}">
          <button type="button" name="button" class="btn btn-default">
            <i class="fa fa-tag" aria-hidden="true"></i>
            Add new version for {{ app.name }}
          </button>
        </a>
      </p>

      <p>
        <a href="{% url 'softhub:app_executable_upload' app.id %}">
          <button type="button" name="button" class="btn btn-default">
            <i class="fa fa-cube" aria-hidden="true"></i>  Add new executable for {{ app.name }}
          </button>
        </a>
      </p>

      <p>
        <a href="{% url 'softhub:app_update' app.id %}">
          <button type="button" name="button" class="btn btn-default">
            <i class="fa fa-wrench" aria-hidden="true"></i>  Edit app details
          </button>
        </a>
      </p>
    </div>

    <div class="col-md-12">
      <p>
        {% include "./app_versions_table.html" %}
      </p>
    </div>

    <div class="col-md-12">
      <p>
        {% include "./app_executables_table.html" %}
      </p>
    </div>

  </div>
</div>

softhub/templates/softhub/application_detail/components/app_downloads.html
<!--
  Shows a panel containing all the versions and executables for the current
  Application.
-->

<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title"> Download </h2>
  </div>

  <div class="panel-body">
    <p>
      {% if linux %}
        <a href="{{ linux.executable_file.url }}">
          <div class="col-md-4 text-center">
            <i class="fa fa-linux fa-4x" aria-hidden="true"></i>
          </div>
        </a>
      {% else %}
        <div class="col-md-4 text-center">
          <i class="fa fa-linux fa-4x" aria-hidden="true"></i>
        </div>
      {% endif %}

      {% if windows %}
        <a href="{{ windows.executable_file.url }}">
          <div class="col-md-4 text-center">
            <i class="fa fa-windows fa-4x" aria-hidden="true"></i>
          </div>
        </a>
      {% else %}
        <div class="col-md-4 text-center">
          <i class="fa fa-windows fa-4x" aria-hidden="true"></i>
        </div>
      {% endif %}

      {% if osx %}
        <a href="{{ osx.executable_file.url }}">
          <div class="col-md-4 text-center">
            <i class="fa fa-apple fa-4x" aria-hidden="true"></i>
          </div>
        </a>
      {% else %}
        <div class="col-md-4 text-center">
          <i class="fa fa-apple fa-4x" aria-hidden="true"></i>
        </div>
      {% endif %}

      {% if not linux and not osx and not windows %}
        <p>
          No executable has been uploaded for the latest version of {{ app }}.
        </p>
      {% endif %}

      <br>

      <!--TODO
      <p class="text-center">
        <button type="button" name="button" class="btn btn-default">
          See all the versions
        </button>
      </p> -->

    </p>
  </div>
</div>

softhub/templates/softhub/application_detail/components/app_executables_table.html
<!--
  Shows a table containing all the versions and executables for the current
  Application and buttons to edit them.
-->

<button type="button"
        name="button"
        class="btn btn-default"
        data-toggle="button"
        id="show-executables-table-btn">
  <i class="fa fa-wrench" aria-hidden="true"></i>  Edit executables
</button>

<table class="table table-striped table-hover" id="app-executables-table" style="display:none">
  <thead>
    <tr>
      <th>Version</th>
      <th>Executable</th>
      <th>Edit Executable</th>
    </tr>
  </thead>

  <tbody>
    {% for version in versions  %}
      {% for exe in executables %}
        {% if exe.version == version %}
          <tr>
            <th scope="row">{{ version }} </th>
            <td> {{ exe }}</td>
            <td>
              <a href="{% url 'softhub:executable_update' exe.id %}">
                <button type="button" name="button" class="btn btn-default">
                  Edit
                </button>
              </a>
            </td>
          </tr>
        {% endif %}
      {% endfor %}
    {% endfor %}
  </tbody>
</table>

softhub/templates/softhub/application_detail/components/app_review.html
{# <div class="row">#}

{# </div>#}

softhub/templates/softhub/application_detail/components/app_summary.html
<!--
  Shows simple informations for an application.
-->

<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title"> {{ app.name }} </h1>
  </div>

  <div class="panel-body">
    <div class="col-md-4">
      <div class="thumbnail">
        {% if app.icon %}
          <img src={{ app.icon.url }}
            class="fixed-img-size"
            alt={{ app.description }}>
        {% endif %}
      </div>
    </div>

    <div class="col-md-8">
      <p>
        <b>Developer</b>: {{ app.developer }} <br>
        <b>License</b>: {% if app.license %} {{ app.license }}
          {% else %}
            No license specified
          {% endif %}
        <br>

        <b>Website</b>: ...<br>
      </p>

      <p>
        <b>Description</b>
        <br>
        {{ app.description }}
      </p>
    </div>
  </div>
</div>

softhub/templates/softhub/application_detail/components/app_versions_table.html
<!--
  Shows a table containing all the versions and executables for the current
  Application and buttons to edit them.
-->

<button type="button"
        name="button"
        class="btn btn-default"
        data-toggle="button"
        id="show-versions-table-btn">
  <i class="fa fa-wrench" aria-hidden="true"></i>   Edit versions
</button>

<table class="table table-striped table-hover" id="app-versions-table" style="display:none">
  <thead>
    <tr>
      <th>Version</th>
      <th>Edit Version</th>
    </tr>
  </thead>

  <tbody>
    {% for version in versions  %}
      <tr>
        <th scope="row">{{ version }} </th>
        <td>
          <a href="{% url 'softhub:version_update' version.id %}">
            <button type="button" name="button" class="btn btn-default">
              Edit
            </button>
          </a>
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

softhub/templates/softhub/application_detail/components/rating.html
<!--
  Displays a numeric rating in stars.

  Use this template by setting a "rating" context variable or passing this value
  like that:
  {# {% include "../path/to/rating.html" with rating=app.getAverageRating showNumericRating=False %} #}
-->

{% load extra_tags_and_filters %}

{# TODO remove hardcoded value! Also in app_review.html #}
{% for star in 5|times %}
  {% if star <= rating|to_int %}
    <span class="glyphicon glyphicon-star"></span>
  {% else %}
    <span class="glyphicon glyphicon-star-empty"></span>
  {% endif %}
{% endfor %}

{% if rating and showNumericRating %}
  {{ rating }} stars <br>
{% endif %}

softhub/templates/softhub/application_detail/components/recommended_items.html
<!--
  Shows a container of recommended applications. Needs to be improved because
  doesn't center the icon of the application.
-->

  <p class="lead">Recommended Apps</p>

  {% for a in apps %}
    {# Application small box #}
    <a href={% url 'softhub:app_detail' a.id %}>
      <div class="recommended-items col-md-12">
        <div class="media">
          <div class="media-left">
              <img src="{{ a.icon.url }}" alt="{{ a }}" class="media-object fixed-very-small-img-size">
          </div>

          <div class="media-body">
            <h4 class="media-heading">{{ a.name }}</h4>
            <p> {{ a.description|truncatechars:50 }} </p>
          </div>
        </div>
      </div>
    </a>

    <hr>
  {% endfor %}

softhub/templates/softhub/application_detail/components/review_form.html
{# <div class="row">#}

  {# <div class="col-md-6">#}
    <h3> Leave a review </h3>
    <form action="" method="post">
      {% csrf_token %}
      {% load crispy_forms_tags %}
      {{ form|crispy }}

      <div class="text-right">
        <input type="submit" value="Submit" class="btn btn-success">
      </div>

    </form>
  {# </div>#}
{# </div>#}

softhub/templates/softhub/application_detail/components/reviews_list.html
{% if reviews %}
  {% for review in reviews %}
    <div class="col-md-12" id={{ review.id }}>
      <strong>
        {{ review.user }}
      </strong>

      {% include "./rating.html" with rating=review.rating.value %}

      {# Show as a date or as a delta ? Eg: "21 December 2017" or "3 days ago" ?#}
      <span class="pull-right"> {{ review.date }} </span>

      <p>
        {{ review.text }}
      </p>
      <hr>
    </div>
  {% endfor %}
{% else %}
  <h3> No reviews for {{ app }} </h3>
{% endif %}